// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mklbbeqyfkyvbbdemtzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rbGJiZXF5Zmt5dmJiZGVtdHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNzg1NDUsImV4cCI6MjA3MzY1NDU0NX0.y9LwjzrLKxnc2rlRFyb5mYP1yUeAfoEfzg841elZjj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});